# _config.yml

# --- 필수 설정 ---
# remote_theme 방식을 사용해 plainwhite 테마를 불러옵니다.
remote_theme: samarsault/plainwhite-jekyll

# --- 기본 정보 (원하는 대로 수정하세요) ---
title: Lemonzamong's Blog # 블로그 제목
description: "기술과 일상을 기록하는 공간입니다." # 블로그 설명
url: "https://lemonzamong.github.io" # 본인 블로그 주소
baseurl: "" # 비워두세요.

# --- Plainwhite 테마 커스텀 설정 (설명서 참고하여 수정) ---
plainwhite:
  name: Lemon Zamong # 사이드바에 표시될 이름
  tagline: Developer & Creator # 이름 아래에 표시될 태그라인
  date_format: "%b %-d, %Y"

  # 소셜 링크 (사용하지 않는 것은 지워도 됩니다)
  social_links:
    instagram: jjjun_04
    github: lemonzamong
    linkedIn: in/hyeokjun-kwon-6022912b1

  # 검색 기능 활성화
  search: true